- name: playbook to install and run nginx
  hosts: web
  become: yes
  tasks: 
  - name: installing nginx
    ansible.builtin.yum:
      name: nginx
      state: present 
  - name: start nginx service
    ansible.builtin.service: 
      name: nginx
      state: started
       
  