- name: installing and starting catalogue service
  hosts: catalogue
  become: yes
  tasks: 
  - name: setting nodejs repos
    ansible.builtin.shell: 'curl -sL https://rpm.nodesource.com/setup_lts.x | bash'

  - name: installing nodejs
    ansible.builtin.yum:
     name: nodejs
     state: installed
    
  - name: checking user exists or not
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true

  - name: if user not  exists creating user
    ansible.builtin.user:
     name: roboshop
    when: output.rc != 0

  - name: checking directory exists or not 
    ansible.builtin.stat: 
      path: /app
    register: directory
  - name: printing output directory checking
    ansible.builtin.debug:
      msg: "output: {{directory}} 
      
