- name: checking user exists or not
  ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true

- name: if user not  exists creating user
  ansible.builtin.user:
     name: roboshop
  when: output.rc != 0

- name: checking directory exists or not 
  ansible.builtin.stat: 
      path: /app
      register: directory
- name: printing output directory checking
  ansible.builtin.debug:
      msg: "output: {{directory}}"
- name: creating directory app if not exists
  ansible.builtin.file:
     path: /app
     state: directory
  when: directory.stat.exists == false