- name: copying mongo repo from common role folder
  become: yes
  ansible.builtin.import_role: 
    name: common
    tasks_from: mongorepo
- name: start mongod service
  ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes

- name: allowing mongodb to access form remote servers
  ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: 127.0.0.1
      replace: 0.0.0.0
- name: restart mongod
  ansible.builtin.service:
     name: mongod
     state: restarted 
    