- name: installing and uninstalling packages
  hosts: node
  become: yes 
  tasks:
  - name: installing and uninstalling
    ansible.builtin.yum:
     name: "{{item.name}}"
     state: "{{item.state}}" 
    loop:
    - {name: 'nginx' , state: 'installed'}
    - {name: 'postfix', state: 'absent'}
    - {name: 'mailx', state: 'absent'}
