- name: installing list of packages
  hosts: node
  become: yes
  tasks: 
  - name: installing packages
    ansible.builtin.yum:
      name: "{{item}}"         #loop will give variable item 
      state: installed
    loop:
    - nginx
    - postfix
    - mailx