- name: variables from prompt 
  hosts: localhost 
  vars_prompt:
  - name: username
    prompt: please enter username
    private: false #you can see values entered on prompt
  - name: password
    prompt: please enter password 
    private: true #you can't see values entered on prompt  

  tasks: 
  - name: printing variables got from prompt
    ansible.builtin.debug:
      msg: "username entered {{username}}, password entered {{password}}" 