- name: variables from files
  hosts: localhost 
  vars_files: 
  - variables-file.yaml
  tasks: 
  - name: printing variables
    ansible.builtin.debug: 
      msg: "hi am {{name}} , learning {{course}}" 